import React, { useState, useEffect } from 'react'
import type { AppProps } from 'next/app'
import { Provider } from 'next-auth/client'
import Head from 'next/head'

import '@/styles/globals.css'
import { Header } from '@/components'
import { LoadingProvider } from '@/store/loading'

const MyApp = ({ Component, pageProps }) => {
	return (
		<Provider session={pageProps.session}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<LoadingProvider>
				<main>
					<Header />

					<Component {...pageProps} />
				</main>
			</LoadingProvider>
		</Provider>
	)
}
export default MyApp
