import React from 'react'
import type { AppProps } from 'next/app'
import { Provider } from 'next-auth/client'
import Head from 'next/head'

import { Header } from '@/components'
import '../styles/globals.css'

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <Provider session={pageProps.session}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Header />
        <Component {...pageProps} />
      </main>
    </Provider>
  )
}
export default MyApp
